### ISSUE TITLE
Use proper html & sign

### ISSUE THREAD

**Issue by sangjunp4rk** [keltoumahfid/prj-rev-bwfs-dasmoto#1]
Use the html & sign instead of just &, which is `&amp;` Continue doing this in the future for all special symbols. You can find all of them here https://www.ascii.cl/htmlcodes.htm

Finally, make sure to separate your html and css code. Using css selectors make it easier to change multiple aspects of your website at once instead of updating each individual specification.

**Comment by keltoumahfid** [comment]
Will do - thanks a lot!
